### ISSUE TITLE
Errors on derived products with empty masks 

### ISSUE THREAD

**Issue by akleroy** [akleroy/phangs_imaging_scripts#236]
@low-sky and @e-koch and @1054 - I am seeing crashes when masks are empty in the latest python versions. Just tagging it here for tracking down at some point. Close (or I will close) if this is fixed or not really an issue.

**Comment by akleroy** [comment]
@low-sky : 

Traceback (most recent call last):
  File "run_derived_mhongoose-alma.py", line 78, in <module>
    this_der.loop_derive_products(do_convolve = False, do_noise = False, 
  File "/data/tycho/0/leroy.42/reduction/alma/phangs_imaging_scripts/phangsPipeline/handlerDerived.py", line 267, in loop_derive_products
    self.task_generate_moments(
  File "/data/tycho/0/leroy.42/reduction/alma/phangs_imaging_scripts/phangsPipeline/handlerDerived.py", line 1019, in task_generate_moments
    moment_generator(
  File "/data/tycho/0/leroy.42/reduction/alma/phangs_imaging_scripts/phangsPipeline/scMoments.py", line 157, in moment_generator
    moment_map, error_map = func(
  File "/data/tycho/0/leroy.42/reduction/alma/phangs_imaging_scripts/phangsPipeline/scDerivativeRoutines.py", line 919, in write_tmax
    lo = np.min(np.where(mask_spec))
  File "<__array_function__ internals>", line 5, in amin
  File "/home/leroy.42/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2879, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/home/leroy.42/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by low-sky** [comment]
Addressed in #241
